pim_enrich_associationtype_index:
    path: /
    defaults: { _controller: pim_enrich.controller.association_type:indexAction }

pim_enrich_associationtype_create:
    path: /create
    defaults: { _controller: pim_enrich.controller.association_type:createAction }

pim_enrich_associationtype_edit:
    path: /{code}/edit
    defaults: { _controller: pim_enrich.controller.association_type:editAction }
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_associationtype_rest_index:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.association_type:indexAction }
    methods: [GET]

pim_enrich_associationtype_rest_get:
    path: /rest/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.association_type:getAction }
    methods: [GET]
    requirements:
        identifier: '[a-zA-Z0-9_]+'

pim_enrich_associationtype_rest_post:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.association_type:postAction }
    methods: [POST]
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_associationtype_rest_remove:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.association_type:removeAction }
    methods: [DELETE]
    requirements:
        code: '[a-zA-Z0-9_]+'
