pim_enrich_channel_index:
    path: /
    defaults: { _controller: pim_enrich.controller.channel:indexAction }

pim_enrich_channel_create:
    path: /create
    defaults: { _controller: pim_enrich.controller.channel:createAction }

pim_enrich_channel_edit:
    path: /{code}/edit
    defaults: { _controller: pim_enrich.controller.channel:editAction }
    requirements:
        code: '[a-zA-Z0-9_]+'


pim_enrich_channel_rest_index:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.channel:indexAction }
    methods: [GET]

pim_enrich_channel_rest_get:
    path: /rest/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.channel:getAction }
    methods: [GET]
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_channel_rest_post:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.channel:postAction }
    methods: [POST]

pim_enrich_channel_rest_put:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.channel:putAction }
    methods: [PUT]
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_channel_rest_remove:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.channel:removeAction }
    methods: [DELETE]
    requirements:
        code: '[a-zA-Z0-9_]+'
