pim_enrich_family_index:
    path: /
    defaults: { _controller: pim_enrich.controller.family:indexAction }

pim_enrich_family_create:
    path: /create
    defaults: { _controller: pim_enrich.controller.family:createAction }

pim_enrich_family_edit:
    path: /{code}/edit
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_family_rest_index:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.family:indexAction }
    methods: [GET]

pim_enrich_family_rest_get:
    path: /rest/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.family:getAction }
    requirements:
        identifier: '[a-zA-Z0-9_]+'
    methods: [GET]

pim_enrich_family_rest_put:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.family:putAction }
    requirements:
        code: '[a-zA-Z0-9_]+'
    methods: [PUT]

pim_enrich_family_rest_remove:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.family:removeAction }
    requirements:
        code: '[a-zA-Z0-9_]+'
    methods: [DELETE]
